version: "3"
services:
  parrot-rest:
    image: parrot-rest
    ports:
      - 8080:8080
    links:
      - redis:redis
    environment:
      - spring.redis.url=http://redis:6379
  redis:
    image: redis:3
    ports:
      - 6379:6379
    
networks:
  default:
    driver: bridge
